# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version_fabric=1.2.3
version_neoforge_curios=1.2.3
version_neoforge_accessories=1.2.3
group=com.cozary.nameless_trinkets
java_version=21

# Common
minecraft_version=1.21.10
mod_name=Nameless Trinkets
mod_author=Cozary
mod_id=nameless_trinkets
license=All Rights Reserved
credits=Thank you for downloading my mod! uwu
description=Add powerful trinkets, which you will find when exploring the world.
minecraft_version_range=[1.21.10, 1.22)
issueTrackerURL=https://github.com/Cozary/Nameless-Trinkets/issues
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Accessories https://modrinth.com/mod/accessories/versions
accessories_version=1.4.3-beta

# Curios API https://modrinth.com/mod/curios/versions
curios_version=13.0.0+1.21.10

# owo-lib https://modrinth.com/mod/owo-lib/versions
owo_version_fabric=0.12.24+1.21.9
owo_version_neoforge=0.12.28+1.21.10

# Fabric https://fabricmc.net/develop/
fabric_version=0.138.4+1.21.10
fabric_loader_version=0.18.2

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.10.64
neoforge_loader_version_range=[4,)

# Publishing
mod_publish_version=0.8.4
dry_run=false
curseforge_project_id=541466
modrinth_project_id=yGp7IenE

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
