# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version_fabric=1.2.4
version_neoforge_curios=1.2.3
version_neoforge_trinkets=1.0.0
group=com.cozary.nameless_trinkets
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Nameless Trinkets
mod_author=Cozary
mod_id=nameless_trinkets
license=All Rights Reserved
credits=Thank you for downloading my mod! uwu
description=Add powerful trinkets, which you will find when exploring the world.
minecraft_version_range=[26.1.2, 26.2)
issueTrackerURL=https://github.com/Cozary/Nameless-Trinkets/issues
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Trinkets Updated https://modrinth.com/mod/trinkets-updated
trinkets_version=4.0.0-beta.2+26.1

# Curios API https://modrinth.com/mod/curios/versions
curios_version=15.0.0-beta.2+26.1.2

# Fabric https://fabricmc.net/develop/
fabric_version=0.150.0+26.1.2
fabric_loader_version=0.19.3

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.73
neoforge_loader_version_range=[4,)

# Publishing
mod_publish_version=0.8.4
dry_run=false
curseforge_project_id=541466
modrinth_project_id=yGp7IenE

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
