site_name: Nameless Trinkets Wiki
site_url: https://nameless-trinkets.wiki
repo_url: https://github.com/Cozary/Nameless-Trinkets
repo_name: Nameless Trinkets
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  name: material
  palette:
    - primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting more slots: slots.md
  - How to obtain trinkets: obtaining.md
  - Recycling Trinkets: recycle.md
  - Tags: tags.md
  - Common Config: common_config.md
  - Loot Tables: loot_tables.md
  - Trinkets:
    - Trinket Bundle: trinkets/trinket_bundle.md
    - Amphibious Hands: trinkets/amphibious_hands.md
    - Blindfold: trinkets/blindfold.md
    - Blaze Nucleus: trinkets/blaze_nucleus.md
    - Broken Ankh: trinkets/broken_ankh.md
    - Broken Magnet: trinkets/broken_magnet.md
    - Callus: trinkets/callus.md
    - Cracked Crown: trinkets/cracked_crown.md
    - Creeper Sense: trinkets/creeper_sense.md
    - Dark Nelumbo: trinkets/dark_nelumbo.md
    - Dragon's Eye: trinkets/dragons_eye.md
    - Dying Star: trinkets/dying_star.md
    - Electric Paddle: trinkets/electric_paddle.md
    - Ethereal Wings: trinkets/ethereal_wings.md
    - Explosion Proof Jacket: trinkets/explosion_proof_jacket.md
    - Experiencie Battery: trinkets/experience_battery.md
    - Experience Magnet: trinkets/experience_magnet.md
    - Fate Emerald: trinkets/fate_emerald.md
    - Fertilizer: trinkets/fertilizer.md
    - Four Leaf Clover: trinkets/four_leaf_clover.md
    - Fragile Cloud: trinkets/fragile_cloud.md
    - Fractured Nullstone: trinkets/fractured_nullstone.md
    - Ghast Eye: trinkets/ghast_eye.md
    - Gills: trinkets/gills.md
    - God's Crown: trinkets/gods_crown.md
    - Ice Cube: trinkets/ice_cube.md
    - Light Gloves: trinkets/light_gloves.md
    - Lucky Rock: trinkets/lucky_rock.md
    - Miner's Soul: trinkets/miners_soul.md
    - Missing Page: trinkets/missing_page.md
    - Moon Stone: trinkets/moon_stone.md
    - Nelumbo: trinkets/nelumbo.md
    - Puffer Fish Liver: trinkets/puffer_fish_liver.md
    - Pocket Lightning Rod: trinkets/pocket_lightning_rod.md
    - Rage Mind: trinkets/rage_mind.md
    - Reforger: trinkets/reforger.md
    - Resonant Heart: trinkets/resonant_heart.md
    - Reverse Card: trinkets/reverse_card.md
    - Scarab Amulet: trinkets/scarab_amulet.md
    - Shrinking Veil: trinkets/shrinking_veil.md
    - Sigil Of Baphomet: trinkets/sigil_of_baphomet.md
    - Sleeping Pills: trinkets/sleeping_pills.md
    - Speed Force: trinkets/speed_force.md
    - Spider Legs: trinkets/spider_legs.md
    - Super Magnet: trinkets/super_magnet.md
    - Tear Of The Sea: trinkets/tear_of_the_sea.md
    - Tick: trinkets/tick.md
    - Titan's Mark: trinkets/titans_mark.md
    - True Heart Of The Sea: trinkets/true_heart_of_the_sea.md
    - Vampire Blood: trinkets/vampire_blood.md
    - What...? Magnet: trinkets/what_magnet.md
    - Wooden Stick: trinkets/wooden_stick.md
    - Woundbearer: trinkets/woundbearer.md

  - FAQ: faq.md